esphome:
  name: esp32s2-219
  friendly_name: esp32s2-219

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

i2c:
  sda: GPIO35
  scl: GPIO33
  scan: true

sensor:
  - platform: bmp280_i2c
    temperature:
      name: "BMP280 Temperature"
    pressure:
      name: "BMP280 Pressure"
    address: 0x76
    update_interval: 60s

output:
  - platform: gpio
    pin: GPIO15
    id: led

light:
  - platform: binary
    name: "Onboard LED"
    output: led

# Enable Home Assistant API
api:
  encryption:
    key: "9WjjI0NRH9Tn1zyIxFmlAEyWO6q2dhladnk6x7mDsek="

ota:
  - platform: esphome
    password: "f0b936a684cd074aa2b12efb66e477a0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # https://esphome.io/components/wifi.html#manual-ips
    static_ip: 192.168.0.219
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32S2-219 Fallback Hotspot"
    password: "xxIpZ9IZhQZ3"

captive_portal:
    