esphome:
  name: esp32s2-12
  friendly_name: esp32s2-12

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

output:
  - platform: gpio
    pin: GPIO15
    id: led

light:
  - platform: binary
    name: "Onboard LED"
    output: led

# Enable Home Assistant API
api:
  encryption:
    key: "a5ejVqE55JZCxD5VBIAxfgw4bP9O5+tpHtJD2DogzXw="

ota:
  - platform: esphome
    password: "ccb670dd234bf7d1cb8e1f5222403ddd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32S2-12 Fallback Hotspot"
    password: "cR9kIltxwFfr"

captive_portal:
    