esphome:
  name: esp32s2-218
  friendly_name: esp32s2-218

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

output:
  - platform: gpio
    pin: GPIO15
    id: led

light:
  - platform: binary
    name: "Onboard LED"
    output: led

# Enable Home Assistant API
api:
  encryption:
    key: "8OQ28ggpiS1iQEyEikiqERBZRgQbg12i7YhkbNDnpkU="

ota:
  - platform: esphome
    password: "228caa2dbe5530a177013562280ce2e2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # https://esphome.io/components/wifi.html#manual-ips
    static_ip: 192.168.0.218
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32S2-218 Fallback Hotspot"
    password: "dzdgpG37TTyB"

captive_portal:
    