esphome:
  name: esp32s2-217
  friendly_name: esp32s2-217

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

# i2c:
#   sda: GPIO35
#   scl: GPIO33
#   scan: true

# sensor:
#   - platform: bmp280_i2c
#     temperature:
#       name: "BMP280 Temperature"
#     pressure:
#       name: "BMP280 Pressure"
#     address: 0x76
#     update_interval: 60s

output:
  - platform: gpio
    pin: GPIO15
    id: led

light:
  - platform: binary
    name: "Onboard LED"
    output: led

# Enable Home Assistant API
api:
  encryption:
    key: "/4QG0MXzBxemvG1PlA6SArQb3p7qxfJ3S5WV5/BKPTk="

ota:
  - platform: esphome
    password: "69dfc608a899a8aac0fbe626ee20651f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # https://esphome.io/components/wifi.html#manual-ips
    static_ip: 192.168.0.217
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32S2-217 Fallback Hotspot"
    password: "0LB6hETt0t25"

captive_portal:
    