esphome:
  name: esp32s2-led-test

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

output:
  - platform: gpio
    pin: GPIO15
    id: led

light:
  - platform: binary
    name: "Onboard LED"
    output: led


