esphome:
  name: esp32s2-214
  friendly_name: esp32s2-214

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

# i2c:
#   sda: GPIO35
#   scl: GPIO33
#   scan: true

# sensor:
#   - platform: bmp280_i2c
#     temperature:
#       name: "BMP280 Temperature"
#     pressure:
#       name: "BMP280 Pressure"
#     address: 0x76
#     update_interval: 60s

output:
  - platform: gpio
    pin: GPIO15
    id: led

light:
  - platform: binary
    name: "Onboard LED"
    output: led

# Enable Home Assistant API
api:
  encryption:
    key: "XoTEiG2W4EcVCU70ieWl2ULUNHVjwR8gqCVEavN8FTY="

ota:
  - platform: esphome
    password: "350df9ef03f8694769bacc87d73eb92e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # https://esphome.io/components/wifi.html#manual-ips
    static_ip: 192.168.0.214
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32S2-214 Fallback Hotspot"
    password: "IbX09dAvhjEu"

captive_portal:
    