esphome:
  name: esp32s2-213
  friendly_name: esp32s2-213

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "PEvH5ryvmyrV61iYqVfJ3igOKUGfknIxCqHY7QBQe/o="

ota:
  - platform: esphome
    password: "bd4aca77184432d2d2993e7f305b5bdf"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32S2-213 Fallback Hotspot"
    password: "3Uu26j12uFnV"

captive_portal:
    